name: alira_cafe_stok
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.10.5
  flutter_barcode_scanner: ^2.0.0
  qr_code_scanner: ^1.0.1
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  fl_chart: ^0.66.0
  intl: ^0.18.1
  path: ^1.8.3
  audioplayers: ^5.2.1
  mobile_scanner: ^3.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "app_alira.png" # PNG ikonun dosya yolu
  android: true
  ios: true

flutter:
  uses-material-design: true
assets:
    - beep.mp3